/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as LogRouteImport } from './routes/log'
import { Route as IndexRouteImport } from './routes/index'

const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/overview': typeof OverviewRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/overview': typeof OverviewRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/log': typeof LogRoute
  '/overview': typeof OverviewRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/log' | '/overview' | '/settings' | '/sync'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/log' | '/overview' | '/settings' | '/sync'
  id: '__root__' | '/' | '/log' | '/overview' | '/settings' | '/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogRoute: typeof LogRoute
  OverviewRoute: typeof OverviewRoute
  SettingsRoute: typeof SettingsRoute
  SyncRoute: typeof SyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogRoute: LogRoute,
  OverviewRoute: OverviewRoute,
  SettingsRoute: SettingsRoute,
  SyncRoute: SyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
